export const mapsData = [
  {
    groupId: '0',
    groupName: 'League Of Legends',
    name: 'League of Legends',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Flol-map.png?alt=media&token=6a6e88c4-514d-4a05-9b3c-f95627152dd9',
  },
  {
    groupId: '1',
    groupName: 'Call of Duty: Cold War',
    name: 'Apocalypse',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fapocalypse.jpg?alt=media&token=405e9984-2563-4284-aa3d-e6ccb8a4c8e7',
  },
  {
    groupId: '1',
    groupName: 'Call of Duty: Cold War',
    name: 'Checkmate',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fcheckmate.jpg?alt=media&token=d3995e12-cc8f-450c-97e1-a03a19cadeae',
  },
  {
    groupId: '1',
    groupName: 'Call of Duty: Cold War',
    name: 'Express',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fexpress.jpg?alt=media&token=d74024cf-4094-4774-bbdd-78aa5b4ca4c7',
  },
  {
    groupId: '1',
    groupName: 'Call of Duty: Cold War',
    name: 'Garrison',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fgarrison.jpg?alt=media&token=f916928a-8eaf-4107-9336-8a7a83789ed1',
  },
  {
    groupId: '1',
    groupName: 'Call of Duty: Cold War',
    name: 'Maimi',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fmaimi.jpg?alt=media&token=eed05f42-46ef-4450-857f-3291f96c8fc8',
  },
  {
    groupId: '1',
    groupName: 'Call of Duty: Cold War',
    name: 'Moscow',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fmoscow.jpg?alt=media&token=65a746b0-e482-4107-8119-a5d3158dfbdf',
  },
  {
    groupId: '1',
    groupName: 'Call of Duty: Cold War',
    name: 'Raid',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fraid.jpg?alt=media&token=95f8aa57-6ff1-4bb1-914d-b07f41d1f7f3',
  },
  {
    groupId: '1',
    groupName: 'Call of Duty: Cold War',
    name: 'Standoff',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fstandoff.jpg?alt=media&token=99fb03e4-b4b1-4f95-ae1c-391de216827c',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Paris',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2FParis-overwatch.jpg?alt=media&token=f5797ba4-56a9-4955-8d9a-b1a1210c7136',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Blizzard World',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fblizzardworld-overwatch.jpg?alt=media&token=979eb405-4463-4095-b3df-e38b16805b83',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Busan',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fbusan-overwatch.jpg?alt=media&token=d220706c-f8da-417d-bf29-308f7e2fee6f',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Dorado',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fdorado-overwatch.jpg?alt=media&token=5078d186-9b4b-4314-aede-2b8503f68785',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Eichenwalde',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Feichenwalde-overwatch.jpg?alt=media&token=501bc008-9162-4704-b140-b18ee436712a',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Hanamura',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fhanamura-overwatch.jpg?alt=media&token=1f271f5c-7a2e-4036-8cfe-ca9a6fb7038a',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Havana',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fhavana-overwatch.jpg?alt=media&token=86531137-fb1b-45fd-8135-a343f6c81b9a',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Junkertown',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fjunkertown-overwatch.jpg?alt=media&token=f0e379c9-fb89-4291-8bde-cae1171b6e69',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: "King's Row",
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fkingsrow-overwatch.jpg?alt=media&token=3dce31ac-3d38-42a8-b9c4-2ef2ade4d53b',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Ilios',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Filios-overwatch.jpg?alt=media&token=2e04a62a-6631-4d9f-b1d7-e22ea2b025fc',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Hollywood',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fhollywood-overwatch.jpg?alt=media&token=69a5935f-8d74-4397-bf47-7fb69644359f',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Horizon Lunar Colony',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fhorizonlunarcolony-overwatch.jpg?alt=media&token=422aa981-4c98-488d-94cf-a4df82311c3d',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Nepal',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fnepal-overwatch.jpg?alt=media&token=3c1de726-4db1-4978-a784-95a2f4c98fc5',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Numbani',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fnumbani-overwatch.jpg?alt=media&token=926554ee-eb00-43b6-8837-db7e7989d901',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Oasis',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Foasis-overwatch.jpg?alt=media&token=39330c2b-b633-43fb-abdc-68a91d46d1a7',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Temple of anubis',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Ftempleofanubis-overwatch.jpg?alt=media&token=83da706b-40ae-4270-ba3a-088e8cdefb5c',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Volskaya Industries',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fvolskayaindustries-overwatch.jpg?alt=media&token=6ecdb72d-aa72-41b7-b343-6abff887c7c8',
  },
  {
    groupId: '3',
    groupName: 'Overwatch',
    name: 'Watchpoint: Gibraltar',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Fwatchpointgibraltar-overwatch.jpg?alt=media&token=d6c58cbc-28df-43cc-96f3-4d7c11c59512',
  },
  {
    groupId: '4',
    groupName: 'Rocket League',
    name: 'Map 1',
    link: 'https://firebasestorage.googleapis.com/v0/b/spark-esport.appspot.com/o/maps%2Frocket-league-1.png?alt=media&token=ee4b8477-9eba-470b-8d6d-60beea138995',
  },
]
