export { GoalSettingPage } from './GoalSettingNewPage'
export { ChooseTeam } from './ChooseTeam'
export { ChoosePlayer } from './ChoosePlayer'
export { CreateGoal } from './CreateGoal'
export { GoalPage } from './GoalPage'
